<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def print_matrix(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            print(" ", matrix[i][j], end = " ")
        print("\n")
        
m = int(input("Enter number of rows of matrix A: "))
n = int(input("Enter number of columns of matrix A: "))
p = int(input("Enter number of rows of matrix B: "))
q = int(input("Enter number of columns of matrix B: "))

if n != p:
    print("Matrix multiplication is not possible")

A = [[0 for j in range(0, n)] for i in range(0, m)]
B = [[0 for j in range(0, q)] for i in range(0, p)]
C = [[0 for j in range(0, q)] for i in range(0, m)]

print("\nMatrix A")
for i in range(m):
    for j in range(n):
        A[i][j] = int(input())
        
print_matrix(A)

print("Matrix B")
for i in range(0, p):
    for j in range(0, q):
        B[i][j] = int(input())

print_matrix(B)

Enter number of rows of matrix A: 2
Enter number of columns of matrix A: 2
Enter number of rows of matrix B: 2
Enter number of columns of matrix B: 2

Matrix A
1
2
3
4
  1   2 

  3   4 

Matrix B
5
6
7
8
  5   6 

  7   8 



In [ ]:
def matrix_mul(A, B):    
    for i in range(len(A)): 
        for j in range(len(B[0])): 
             for k in range(len(B)): 
               C[i][j] += A[i][k] * B[k][j]      
    return C    
print_matrix(matrix_mul(A, B))

  19   22 

  43   50 



<h3> Q2: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
def replace_digits(string):
    m=re.sub("\d","#",string)


In [ ]:
import re
examples = ['234',
              'a2b3c4',
              'abc',
              '#2a$#b%c%561#']
for example in examples:
      new_s = '#' * len(re.sub(r'\D', '', example))
      print('Input = {} \n Output = {}'.format(example, new_s))

Input = 234 
 Output = ###
Input = a2b3c4 
 Output = ###
Input = abc 
 Output = 
Input = #2a$#b%c%561# 
 Output = ####


<h3> Q3: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    index_of_non_empty_cells_list = []

    split_string = string.split(',')
    
    for i in range(len(split_string)):
        if split_string[i] != '_':
            index_of_non_empty_cells_list.append(i)
            
    index_of_non_empty_cells_list.append(len(split_string) - 1)
    
    start = 0
    
    for ele in index_of_non_empty_cells_list:
        cumulative_sum_prev_and_next_value = int(split_string[ele]) if split_string[ele] != '_' else 0
        cumulative_sum_prev_and_next_value += int(split_string[start]) if split_string[start] != '_' and start != ele else 0
        integer_to_replace = cumulative_sum_prev_and_next_value // (ele - start + 1)
        split_string = [integer_to_replace if start <= x <= ele else split_string[x] for x in range(len(split_string))]
        start = ele
    return split_string
    return 



In [ ]:
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q4: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    s1_unique_words_set = set(S1.split(" "))
    s2_unique_words_set = set(S2.split(" "))

    num_of_common_words = len(s1_unique_words_set.intersection(s2_unique_words_set)),
    s1_words_not_in_s2 = s1_unique_words_set - s2_unique_words_set
    s2_words_not_in_s1 = s2_unique_words_set - s1_unique_words_set

    print('a. ', list(num_of_common_words)[0])
    print('b. ', list(s1_words_not_in_s2))
    print('b. ', list(s2_words_not_in_s1))

In [ ]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)


a.  7
b.  ['5', 'F', 'first']
b.  ['3', 'second', 'S']
